.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NODEAPP" "1" "November 2023" "" ""
.
.SH "NAME"
\fBnodeapp\fR
.
.SH "NAME"
nodeapp \- A simple Node\.js web app\.
.
.SH "SYNOPSIS"
\fBnodeapp [\-h] [\-p PORT]\fR
.
.SH "DESCRIPTION"
nodeapp is a program that launches a web app hosted on your computer\.
.
.SH "EXAMPLES"
To host on default port (port 8000):
.
.IP "" 4
.
.nf

nodeapp
.
.fi
.
.IP "" 0
.
.P
To host on a specific port:
.
.IP "" 4
.
.nf

nodeapp \-p <PORT>
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
The Real Finnventor \fIfinnventor@everspaugh\.com\fR
.
.SH "SEE ALSO"
get
.
.P
A program to get stuff from the world wide web\. \fIhttps://github\.com/the\-real\-finnventor/get\fR
